# Generated by Django 4.2.11 on 2024-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainerprofile_memberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
    ]
