# Generated by Django 4.2.11 on 2024-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_memberprofile_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
