# Generated by Django 4.2.11 on 2024-08-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_memberprofile_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.CharField(choices=[('Monthly', 30), ('Quarterly', 90), ('Yearly', 365)], default='Monthly', max_length=50),
            preserve_default=False,
        ),
    ]
