# Generated by Django 4.1 on 2024-09-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workoutplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.PositiveIntegerField(default=1500)),
                ('daily_steps_goal', models.PositiveIntegerField(default=5000)),
                ('sleep_goal', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('water_intake_goal', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
