# Generated by Django 4.1 on 2024-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_goal_sleep_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_status',
            field=models.CharField(choices=[('Member', 'Member'), ('Not_member', 'Not A Member')], default='Not A Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.CharField(blank=True, choices=[('Monthly', 30), ('Quarterly', 90), ('Yearly', 365)], default='Monthly', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('Base', 'Base'), ('Premium', 'Premium'), ('Gold', 'Gold')], max_length=50, null=True),
        ),
    ]
