# Generated by Django 4.1 on 2024-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_membership_membership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_status',
            field=models.CharField(choices=[('Member', 'Member'), ('Not A Member', 'Not_member')], max_length=50),
        ),
    ]
