# Generated by Django 4.1 on 2024-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_membership_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='days_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.CharField(blank=True, choices=[('Monthly', 30), ('Quarterly', 90), ('Yearly', 365)], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_status',
            field=models.CharField(choices=[('Member', 'Member'), ('Not A Member', 'Not A Member')], default='Not A Member', max_length=50),
        ),
    ]
