# Generated by Django 4.1 on 2024-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_membership_days_left_alter_membership_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
