# Generated by Django 4.1 on 2024-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_memberprofile_height_memberprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=10),
        ),
    ]
