# Generated by Django 5.1 on 2024-10-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_memberprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='days_left',
        ),
    ]
